// src/constants/floorplanItems.js

// Defines reusable item prototypes for the floor plan editor
export const ITEM_PROTOTYPES = {
  table_small: {
    type: "table",
    w: 80,
    h: 80,
    shape: "round",
    color: "#eab308",
  },
  table_square: {
    type: "table",
    w: 80,
    h: 80,
    shape: "square",
    color: "#f97316",
  },
  table_large: {
    type: "table",
    w: 140,
    h: 80,
    shape: "rect",
    color: "#f97316",
  },
  chair: {
    type: "chair",
    w: 22,
    h: 22,
    shape: "round",
    color: "#60a5fa",
  },
  stage: {
    type: "stage",
    w: 300,
    h: 80,
    shape: "rect",
    color: "#6b7280",
  },
  light_small: {
    type: "light",
    w: 20,
    h: 20,
    shape: "round",
    color: "#fef08a",
  },
  light_medium: {
    type: "light",
    w: 30,
    h: 30,
    shape: "round",
    color: "#fef08a",
  },
  light_large: {
    type: "light",
    w: 40,
    h: 40,
    shape: "round",
    color: "#fef08a",
  },
  piano: {
    type: "piano",
    w: 120,
    h: 60,
    shape: "rect",
    color: "#000000",
  },
  dance_floor: {
    type: "dance_floor",
    w: 200,
    h: 200,
    shape: "square",
    color: "#d1d5db",
  },
  drink_bar: {
    type: "drink_bar",
    w: 150,
    h: 50,
    shape: "rect",
    color: "#7f1d1d",
  },
  cake_table: {
    type: "cake_table",
    w: 60,
    h: 60,
    shape: "square",
    color: "#fbcfe8",
  },
  head_table: {
    type: "head_table",
    w: 200,
    h: 60,
    shape: "rect",
    color: "#db2777",
  },
  walkway_carpet: {
    type: "walkway_carpet",
    w: 300,
    h: 40,
    shape: "rect",
    color: "#b91c1c",
  },
  catering_stand: {
    type: "catering_stand",
    w: 100,
    h: 50,
    shape: "rect",
    color: "#15803d",
  },
  exit_door: {
    type: "exit_door",
    w: 60,
    h: 30,
    shape: "rect",
    color: "#dc2626",
  },
};
